// Core domain types for net.

export type WarmthLevel = "none" | "low" | "medium" | "full";

export interface User {
  id: string;
  display_name: string;
  profile_photo_url: string | null;
  interests: string; // freeform text, never a taxonomy
  cohort: string;
  city: string;
  concentration: string;
  created_at: Date;
}

export interface Thought {
  id: string;
  user_id: string;
  sentence: string;           // the single sentence — the thought itself
  context: string | null;     // up to 3 sentences of background
  image_url: string | null;   // cinematic landscape, generated by ML service
  quality_score: number;      // 0–1, computed by ML service
  created_at: Date;
}

export interface FeedThought extends Thought {
  warmth_level: WarmthLevel;
  // NOTE: never include counts of any kind
}

export interface Reply {
  id: string;
  thought_id: string;
  from_user_id: string;
  content: string;
  accepted: boolean;
  created_at: Date;
}

export interface Conversation {
  id: string;
  thought_id: string;
  participant_a: string;
  participant_b: string;
  started_at: Date;
  last_message_at: Date;
  message_count: number;
}

// Engagement events (internal only, never exposed to users)
export type EngagementEventType =
  | "view_p1"
  | "swipe_p2"
  | "swipe_p3"
  | "type_start"
  | "reply_sent";

export interface EngagementEvent {
  id: string;
  user_id: string;
  thought_id: string;
  event_type: EngagementEventType;
  created_at: Date;
}
