app = 'ohmmmm-silent-surf-1627'
primary_region = 'sjc'

[build]

[deploy]
  release_command = "npm run db:migrate:prod"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[http_service.concurrency]
  type = "requests"
  hard_limit = 250
  soft_limit = 200

[[http_service.checks]]
  interval = "15s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/health"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
